#!/bin/sh
### BEGIN INIT INFO
# Provides:          install-updates
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Installs pending updates
# Description:       Installs any pending radiodan app updates
### END INIT INFO

set -e

# Install any pending services (if any)
/usr/sbin/radiodan-updater install --workspace=/opt/radiodan/updates --target=/opt/radiodan/apps &
