#!/bin/sh
### BEGIN INIT INFO
# Provides:          radiodan-example
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Radiodan Example
# Description:       Example webapp for radiodan
### END INIT INFO

set -e

export NODE_PATH=$NODE_PATH:/usr/lib/node_modules
export LOG_LEVEL=debug


# Must be a valid filename
NAME=radiodan-example
PIDFILE=/var/run/radiodan/$NAME.pid
#This is the command to be run, give the full pathname
DAEMON=/usr/bin/node
DAEMON_OPTS="/opt/radiodan/apps/radiodan-example/current/main.js"

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
    echo -n "Starting daemon: "$NAME
    start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS > /var/log/radiodan/$NAME.log 2>&1
    echo "."
    ;;
  stop)
    echo -n "Stopping daemon: "$NAME
    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
    rm $PIDFILE
    echo "."
    ;;
  restart)
    echo -n "Restarting daemon: "$NAME
    start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
    start-stop-daemon --start --quiet --background --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
    echo "."
    ;;

  *)
    echo "Usage: "$1" {start|stop|restart}"
    exit 1
esac

exit 0
