#!/bin/sh
### BEGIN INIT INFO
# Provides:          wpa-try-adhoc
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Setup adhoc network if networking is not configured
# Description:       Setup adhoc network if netowrking is not configure.
### END INIT INFO

set -e

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

print_ip_address() {
# Print the IP address
    IP=$(ip addr show | grep "inet " | grep -v " lo" | grep -oP "\d+\.\d+\.\d+\.\d+/\d+" | grep -oP "\d+\.\d+\.\d+\.\d+") || true
    if [ "$IP" ]; then
      echo "My IP address is $IP"
    fi
}

do_start() {
    echo -n "Adhoc network configuration: "
    print_ip_address
    /usr/sbin/try_adhoc_network > /var/log/radiodan/adhoc.log 2>&1
}

case "$1" in
    start)
	do_start
	exit 0
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop|status)
        # No-op
        exit 0
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac

exit 0
