#!/bin/sh
### BEGIN INIT INFO
# Provides:          mopidy
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Mopidy
# Description:       Mopidy
### END INIT INFO

NAME=mopidy
PIDFILE=/var/run/$NAME.pid
DAEMON=/usr/bin/mopidy
DAEMON_OPTS="--config /etc/mopidy/conf.d:/etc/mopidy/mopidy.conf"

case "$1" in
  start)
    echo -n "Starting daemon: "$NAME
    start-stop-daemon --start --quiet --background --no-close --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS > /var/log/$NAME.log 2>&1
    echo "."
    ;;
  stop)
    echo -n "Stopping daemon: "$NAME
    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
    rm $PIDFILE
    echo "."
    ;;
  restart)
    echo -n "Restarting daemon: "$NAME
    start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
    start-stop-daemon --start --quiet --background --no-close --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS > /var/log/$NAME.log 2>&1
    echo "."
    ;;

  *)
    echo "Usage: "$1" {start|stop|restart}"
    exit 1
esac

exit 0
